using System.Collections.Generic;

namespace EmergencyPriority
{
    // Machine-translated UI strings (Options + panels). English is the source of truth; Get() returns the
    // locale string when present, else English. Community corrections welcome.
    public static class Translations
    {
        public static string Get(string key, string locale) =>
            (Loc.TryGetValue(locale, out var lm) && lm.TryGetValue(key, out var lv)) ? lv
            : (En.TryGetValue(key, out var v) ? v : key);

        public static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            { "opt.Enabled.L", "Enable Emergency Priority" },
            { "opt.Enabled.D", "Keeps responding fire engines, ambulances and police cars alive and moving through traffic jams. Off = vanilla behaviour." },
            { "opt.DespawnGuard.L", "Prevent stuck responders from despawning" },
            { "opt.DespawnGuard.D", "Vanilla deletes a responding vehicle once it is flagged as stuck in traffic, and the emergency waits for a re-dispatch. With the guard, the vehicle looks for a new route instead." },
            { "opt.AutoReroute.L", "Re-route around congestion" },
            { "opt.AutoReroute.D", "Vanilla plans the route once, at dispatch. With this on, a responder that sits blocked in a jam requests a fresh route that accounts for current traffic." },
            { "opt.RerouteAfterSeconds.L", "Re-route after (seconds blocked)" },
            { "opt.RerouteAfterSeconds.D", "How long a responder must be continuously stuck behind traffic before it looks for a detour." },
            { "opt.GreenLightPriority.L", "Green lights along the route" },
            { "opt.GreenLightPriority.D", "Traffic lights on a responding vehicle's route turn green as it approaches, and stay green until it has passed. This clears the queue of cars in front of it — emergency vehicles already ignore red lights themselves, it is the traffic ahead of them that waits. Uses the game's own signal priority, so normal light phases and pedestrian crossings are still respected." },
            { "opt.GreenLightDistance.L", "Green light distance (metres)" },
            { "opt.GreenLightDistance.D", "How far ahead of a responding vehicle the traffic lights react. A light needs a few seconds to change safely, so a longer distance makes it more likely to already be green on arrival. Shorter distances hold fewer junctions open at once." },
            { "grp.Group", "Responding vehicles" },
            { "grp.GroupLights", "Traffic lights" },
            { "grp.GroupGeneral", "General" },
        };

        public static readonly Dictionary<string, Dictionary<string, string>> Loc = new Dictionary<string, Dictionary<string, string>>
        {
                ["de-DE"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Emergency Priority aktivieren", ["opt.Enabled.D"]="Hält ausrückende Feuerwehr-, Rettungs- und Polizeifahrzeuge am Leben und in Bewegung durch Staus. Aus = Vanilla-Verhalten.", ["opt.DespawnGuard.L"]="Verhindert das Verschwinden festsitzender Einsatzfahrzeuge", ["opt.DespawnGuard.D"]="Vanilla löscht ein ausrückendes Fahrzeug, sobald es als im Stau festsitzend markiert wird, und der Einsatz wartet auf eine erneute Entsendung. Mit dem Schutz sucht das Fahrzeug stattdessen eine neue Route.", ["opt.AutoReroute.L"]="Um Staus herum umleiten", ["opt.AutoReroute.D"]="Vanilla plant die Route nur einmal, bei der Entsendung. Ist dies an, fordert ein Einsatzfahrzeug, das blockiert im Stau steht, eine neue Route an, die den aktuellen Verkehr berücksichtigt.", ["opt.RerouteAfterSeconds.L"]="Umleiten nach (Sekunden blockiert)", ["opt.RerouteAfterSeconds.D"]="Wie lange ein Einsatzfahrzeug ununterbrochen hinter dem Verkehr festsitzen muss, bevor es einen Umweg sucht.", ["opt.GreenLightPriority.L"]="Grüne Welle entlang der Route", ["opt.GreenLightPriority.D"]="Ampeln auf der Route eines ausrückenden Fahrzeugs schalten bei dessen Annäherung auf Grün und bleiben grün, bis es durchgefahren ist. Das räumt die Fahrzeugschlange vor ihm frei — Einsatzfahrzeuge ignorieren rote Ampeln ohnehin selbst, es ist der Verkehr vor ihnen, der wartet. Nutzt die spieleigene Ampelpriorität, sodass normale Ampelphasen und Fußgängerüberwege weiterhin beachtet werden.", ["opt.GreenLightDistance.L"]="Reichweite der grünen Welle (Meter)", ["opt.GreenLightDistance.D"]="Wie weit vor einem ausrückenden Fahrzeug die Ampeln reagieren. Eine Ampel braucht einige Sekunden zum sicheren Umschalten, eine größere Reichweite bedeutet also eher schon Grün bei Ankunft. Kürzere Reichweiten halten weniger Kreuzungen gleichzeitig offen.", ["grp.Group"]="Einsatzfahrzeuge", ["grp.GroupLights"]="Ampeln", ["grp.GroupGeneral"]="Allgemein", },
                ["es-ES"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Activar Emergency Priority", ["opt.Enabled.D"]="Mantiene con vida y en movimiento a los camiones de bomberos, ambulancias y coches de policía que acuden a una emergencia a través de los atascos. Desactivado = comportamiento vanilla.", ["opt.DespawnGuard.L"]="Evitar que los vehículos de emergencia atascados desaparezcan", ["opt.DespawnGuard.D"]="El vanilla elimina un vehículo que acude a una emergencia en cuanto se marca como atascado en el tráfico, y la emergencia espera a un nuevo despacho. Con esta protección, el vehículo busca una nueva ruta en su lugar.", ["opt.AutoReroute.L"]="Desviar para evitar la congestión", ["opt.AutoReroute.D"]="El vanilla planifica la ruta una sola vez, al despachar. Con esto activado, un vehículo que queda bloqueado en un atasco solicita una ruta nueva que tiene en cuenta el tráfico actual.", ["opt.RerouteAfterSeconds.L"]="Desviar tras (segundos bloqueado)", ["opt.RerouteAfterSeconds.D"]="Cuánto tiempo debe estar un vehículo de emergencia continuamente atascado detrás del tráfico antes de buscar un desvío.", ["opt.GreenLightPriority.L"]="Semáforos en verde a lo largo de la ruta", ["opt.GreenLightPriority.D"]="Los semáforos en la ruta de un vehículo de emergencia se ponen en verde cuando este se acerca y siguen en verde hasta que ha pasado. Esto despeja la cola de coches que tiene delante: los vehículos de emergencia ya se saltan los semáforos en rojo por sí mismos, es el tráfico que va delante el que espera. Utiliza la prioridad de semáforos propia del juego, así que se respetan las fases normales y los pasos de peatones.", ["opt.GreenLightDistance.L"]="Distancia de los semáforos en verde (metros)", ["opt.GreenLightDistance.D"]="A qué distancia por delante de un vehículo de emergencia reaccionan los semáforos. Un semáforo necesita unos segundos para cambiar de forma segura, así que una distancia mayor hace más probable que ya esté en verde al llegar. Las distancias más cortas mantienen abiertos menos cruces a la vez.", ["grp.Group"]="Vehículos de emergencia", ["grp.GroupLights"]="Semáforos", ["grp.GroupGeneral"]="General", },
                ["fr-FR"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Activer Emergency Priority", ["opt.Enabled.D"]="Maintient en vie et en mouvement les camions de pompiers, ambulances et voitures de police en intervention à travers les embouteillages. Désactivé = comportement du jeu de base.", ["opt.DespawnGuard.L"]="Empêcher la disparition des véhicules d'intervention bloqués", ["opt.DespawnGuard.D"]="Le jeu de base supprime un véhicule en intervention dès qu'il est signalé comme bloqué dans le trafic, et l'urgence attend une nouvelle affectation. Avec la protection, le véhicule cherche plutôt un nouvel itinéraire.", ["opt.AutoReroute.L"]="Contourner les embouteillages", ["opt.AutoReroute.D"]="Le jeu de base planifie l'itinéraire une seule fois, à l'affectation. Avec cette option, un véhicule d'intervention bloqué dans un embouteillage demande un nouvel itinéraire tenant compte du trafic actuel.", ["opt.RerouteAfterSeconds.L"]="Recalculer l'itinéraire après (secondes bloqué)", ["opt.RerouteAfterSeconds.D"]="Combien de temps un véhicule d'intervention doit rester bloqué en continu derrière le trafic avant de chercher un détour.", ["opt.GreenLightPriority.L"]="Feux verts le long de l'itinéraire", ["opt.GreenLightPriority.D"]="Les feux situés sur l'itinéraire d'un véhicule d'intervention passent au vert à son approche et le restent jusqu'à ce qu'il soit passé. Cela dégage la file de voitures devant lui : les véhicules d'intervention grillent déjà les feux rouges eux-mêmes, c'est le trafic devant eux qui attend. Utilise la priorité de feux propre au jeu, donc les phases normales et les passages piétons restent respectés.", ["opt.GreenLightDistance.L"]="Portée des feux verts (mètres)", ["opt.GreenLightDistance.D"]="À quelle distance devant un véhicule d'intervention les feux réagissent. Un feu met quelques secondes à changer en toute sécurité, une portée plus grande augmente donc les chances qu'il soit déjà vert à l'arrivée. Des portées plus courtes maintiennent moins de carrefours ouverts à la fois.", ["grp.Group"]="Véhicules d'intervention", ["grp.GroupLights"]="Feux de circulation", ["grp.GroupGeneral"]="Général", },
                ["it-IT"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Abilita Emergency Priority", ["opt.Enabled.D"]="Mantiene attivi e in movimento tra il traffico i mezzi di soccorso in intervento: autopompe, ambulanze e volanti della polizia. Disattivato = comportamento originale.", ["opt.DespawnGuard.L"]="Impedisci la scomparsa dei soccorritori bloccati", ["opt.DespawnGuard.D"]="L'originale elimina un veicolo in intervento non appena viene contrassegnato come bloccato nel traffico, e l'emergenza attende un nuovo invio. Con la protezione, il veicolo cerca invece un nuovo percorso.", ["opt.AutoReroute.L"]="Devia intorno alla congestione", ["opt.AutoReroute.D"]="L'originale pianifica il percorso una sola volta, all'invio. Con questa opzione attiva, un soccorritore fermo bloccato in un ingorgo richiede un percorso aggiornato che tiene conto del traffico attuale.", ["opt.RerouteAfterSeconds.L"]="Devia dopo (secondi di blocco)", ["opt.RerouteAfterSeconds.D"]="Per quanto tempo un soccorritore deve restare continuativamente bloccato nel traffico prima di cercare una deviazione.", ["opt.GreenLightPriority.L"]="Semafori verdi lungo il percorso", ["opt.GreenLightPriority.D"]="I semafori sul percorso di un mezzo di soccorso passano al verde al suo avvicinarsi e restano verdi finché non è passato. Questo libera la coda di auto davanti a lui: i mezzi di soccorso passano già con il rosso da soli, è il traffico che li precede ad aspettare. Usa la priorità semaforica propria del gioco, quindi le fasi normali e gli attraversamenti pedonali restano rispettati.", ["opt.GreenLightDistance.L"]="Distanza dei semafori verdi (metri)", ["opt.GreenLightDistance.D"]="A che distanza davanti a un mezzo di soccorso reagiscono i semafori. Un semaforo impiega qualche secondo per cambiare in sicurezza, quindi una distanza maggiore rende più probabile che sia già verde all'arrivo. Distanze più brevi tengono aperti meno incroci per volta.", ["grp.Group"]="Veicoli in intervento", ["grp.GroupLights"]="Semafori", ["grp.GroupGeneral"]="Generale", },
                ["ja-JP"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Emergency Priority を有効化", ["opt.Enabled.D"]="出動中の消防車、救急車、パトカーを渋滞の中でも消滅させず走行させ続けます。オフ = バニラの挙動。", ["opt.DespawnGuard.L"]="立ち往生した緊急車両の消滅を防止", ["opt.DespawnGuard.D"]="バニラでは、渋滞で立ち往生と判定された出動車両を削除し、緊急対応は再出動を待ちます。ガードを有効にすると、その車両は代わりに新しい経路を探します。", ["opt.AutoReroute.L"]="渋滞を迂回して再経路探索", ["opt.AutoReroute.D"]="バニラでは経路は出動時に一度だけ計画されます。これをオンにすると、渋滞で立ち往生した緊急車両が現在の交通状況を反映した新しい経路を要求します。", ["opt.RerouteAfterSeconds.L"]="再経路探索までの時間（立ち往生秒数）", ["opt.RerouteAfterSeconds.D"]="緊急車両が迂回路を探し始めるまでに、渋滞の後ろで連続して立ち往生している必要がある時間。", ["opt.GreenLightPriority.L"]="ルート上の信号を青に", ["opt.GreenLightPriority.D"]="出動中の車両のルート上にある信号機が、接近に合わせて青に変わり、通過し終えるまで青のままになります。これは前方の車列を捌くための機能です。緊急車両自体はもともと赤信号を無視して走行しており、待っているのはその前の一般車両です。ゲーム本来の信号優先制御を使うため、通常の信号サイクルや横断歩道はそのまま尊重されます。", ["opt.GreenLightDistance.L"]="信号が反応する距離（メートル）", ["opt.GreenLightDistance.D"]="出動車両のどれだけ手前から信号機が反応するか。信号が安全に切り替わるには数秒かかるため、距離が長いほど到着時点で既に青になっている可能性が高くなります。距離が短いほど、同時に開放される交差点は少なくなります。", ["grp.Group"]="出動車両", ["grp.GroupLights"]="信号機", ["grp.GroupGeneral"]="全般", },
                ["ko-KR"] = new Dictionary<string, string> { ["opt.Enabled.L"]="긴급 우선 통행 활성화", ["opt.Enabled.D"]="출동 중인 소방차, 구급차, 경찰차가 교통 정체를 뚫고 계속 이동하도록 유지합니다. 꺼짐 = 기본 게임 동작.", ["opt.DespawnGuard.L"]="정체된 출동 차량의 소멸 방지", ["opt.DespawnGuard.D"]="기본 게임은 출동 차량이 교통 정체에 갇힌 것으로 표시되면 이를 삭제하고, 긴급 상황은 재출동을 기다립니다. 이 보호 기능을 켜면 차량이 대신 새 경로를 찾습니다.", ["opt.AutoReroute.L"]="정체 우회 경로 재탐색", ["opt.AutoReroute.D"]="기본 게임은 출동 시 경로를 한 번만 계획합니다. 이 옵션을 켜면 정체에 막혀 멈춰 있는 출동 차량이 현재 교통 상황을 반영한 새 경로를 요청합니다.", ["opt.RerouteAfterSeconds.L"]="재탐색 시점 (막힌 지 초)", ["opt.RerouteAfterSeconds.D"]="출동 차량이 우회로를 찾기 전에 교통에 막혀 연속으로 정체되어야 하는 시간입니다.", ["opt.GreenLightPriority.L"]="경로상의 신호등을 녹색으로", ["opt.GreenLightPriority.D"]="출동 차량의 경로에 있는 신호등이 차량이 접근하면 녹색으로 바뀌고, 통과할 때까지 녹색을 유지합니다. 이는 앞에 늘어선 차량 행렬을 정리하기 위한 기능입니다. 긴급 차량 자체는 원래 적신호를 무시하고 주행하며, 기다리는 것은 그 앞의 일반 차량입니다. 게임 자체의 신호 우선 기능을 사용하므로 일반 신호 주기와 횡단보도는 그대로 존중됩니다.", ["opt.GreenLightDistance.L"]="신호등 반응 거리 (미터)", ["opt.GreenLightDistance.D"]="출동 차량으로부터 얼마나 앞의 신호등이 반응하는지 정합니다. 신호가 안전하게 바뀌려면 몇 초가 걸리므로, 거리가 길수록 도착 시점에 이미 녹색일 가능성이 높습니다. 거리가 짧을수록 동시에 열리는 교차로가 줄어듭니다.", ["grp.Group"]="출동 차량", ["grp.GroupLights"]="신호등", ["grp.GroupGeneral"]="일반", },
                ["pl-PL"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Włącz Emergency Priority", ["opt.Enabled.D"]="Utrzymuje interweniujące wozy strażackie, karetki i radiowozy przy życiu i w ruchu przez korki. Wyłączone = zachowanie z gry podstawowej.", ["opt.DespawnGuard.L"]="Zapobiegaj znikaniu utkniętych pojazdów ratowniczych", ["opt.DespawnGuard.D"]="Gra podstawowa usuwa interweniujący pojazd, gdy zostaje oznaczony jako utknięty w korku, a wezwanie czeka na ponowne wysłanie. Z tą ochroną pojazd zamiast tego szuka nowej trasy.", ["opt.AutoReroute.L"]="Zmiana trasy w celu ominięcia zatorów", ["opt.AutoReroute.D"]="Gra podstawowa planuje trasę tylko raz, przy wysłaniu. Gdy ta opcja jest włączona, pojazd ratowniczy stojący zablokowany w korku żąda nowej trasy uwzględniającej bieżący ruch.", ["opt.RerouteAfterSeconds.L"]="Zmiana trasy po (sekundach blokady)", ["opt.RerouteAfterSeconds.D"]="Jak długo pojazd ratowniczy musi być nieprzerwanie zablokowany w ruchu, zanim zacznie szukać objazdu.", ["opt.GreenLightPriority.L"]="Zielone światło na trasie", ["opt.GreenLightPriority.D"]="Sygnalizacja na trasie interweniującego pojazdu zmienia się na zieloną, gdy ten się zbliża, i pozostaje zielona, dopóki pojazd nie przejedzie. Udrażnia to kolejkę samochodów przed nim — pojazdy ratownicze i tak same ignorują czerwone światło, to ruch przed nimi czeka. Wykorzystuje własny mechanizm priorytetu sygnalizacji z gry, więc normalne fazy świateł i przejścia dla pieszych pozostają zachowane.", ["opt.GreenLightDistance.L"]="Zasięg zielonego światła (metry)", ["opt.GreenLightDistance.D"]="Jak daleko przed interweniującym pojazdem reaguje sygnalizacja. Bezpieczna zmiana świateł trwa kilka sekund, więc większy zasięg zwiększa szansę, że światło będzie już zielone w chwili dojazdu. Mniejszy zasięg utrzymuje otwartych mniej skrzyżowań naraz.", ["grp.Group"]="Pojazdy interweniujące", ["grp.GroupLights"]="Sygnalizacja świetlna", ["grp.GroupGeneral"]="Ogólne", },
                ["pt-BR"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Ativar Emergency Priority", ["opt.Enabled.D"]="Mantém caminhões de bombeiros, ambulâncias e viaturas policiais em atendimento vivos e em movimento no meio dos congestionamentos. Desativado = comportamento original.", ["opt.DespawnGuard.L"]="Impedir que veículos presos desapareçam", ["opt.DespawnGuard.D"]="O jogo original exclui um veículo em atendimento assim que ele é marcado como preso no trânsito, e a emergência aguarda um novo despacho. Com a proteção, o veículo procura uma nova rota em vez disso.", ["opt.AutoReroute.L"]="Recalcular rota contornando o congestionamento", ["opt.AutoReroute.D"]="O jogo original planeja a rota uma única vez, no despacho. Com isto ativado, um veículo que fica bloqueado em um congestionamento solicita uma rota nova que leva em conta o trânsito atual.", ["opt.RerouteAfterSeconds.L"]="Recalcular rota após (segundos bloqueado)", ["opt.RerouteAfterSeconds.D"]="Por quanto tempo um veículo precisa ficar continuamente preso atrás do trânsito antes de procurar um desvio.", ["opt.GreenLightPriority.L"]="Semáforos verdes ao longo da rota", ["opt.GreenLightPriority.D"]="Os semáforos na rota de um veículo em atendimento ficam verdes quando ele se aproxima e permanecem verdes até que ele passe. Isso libera a fila de carros à frente dele: veículos de emergência já avançam o sinal vermelho por conta própria, quem espera é o trânsito à frente deles. Usa a prioridade de semáforos do próprio jogo, então as fases normais e as faixas de pedestres continuam respeitadas.", ["opt.GreenLightDistance.L"]="Distância dos semáforos verdes (metros)", ["opt.GreenLightDistance.D"]="A que distância à frente de um veículo em atendimento os semáforos reagem. Um semáforo leva alguns segundos para mudar com segurança, então uma distância maior aumenta a chance de ele já estar verde na chegada. Distâncias menores mantêm menos cruzamentos abertos ao mesmo tempo.", ["grp.Group"]="Veículos em atendimento", ["grp.GroupLights"]="Semáforos", ["grp.GroupGeneral"]="Geral", },
                ["ru-RU"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Включить Emergency Priority", ["opt.Enabled.D"]="Помогает выезжающим пожарным машинам, каретам скорой помощи и полицейским машинам не застревать и двигаться сквозь пробки. Выкл = поведение оригинала.", ["opt.DespawnGuard.L"]="Не давать застрявшим экстренным машинам исчезать", ["opt.DespawnGuard.D"]="Оригинал удаляет выехавшую машину, как только она помечена застрявшей в пробке, и экстренная служба ждёт повторной отправки. С этой защитой машина вместо этого ищет новый маршрут.", ["opt.AutoReroute.L"]="Объезд заторов", ["opt.AutoReroute.D"]="Оригинал прокладывает маршрут один раз, при отправке. С включённым параметром машина, застрявшая в пробке, запрашивает новый маршрут с учётом текущего трафика.", ["opt.RerouteAfterSeconds.L"]="Перепрокладка через (секунд в заторе)", ["opt.RerouteAfterSeconds.D"]="Сколько времени машина должна непрерывно стоять в пробке, прежде чем начнёт искать объезд.", ["opt.GreenLightPriority.L"]="Зелёный свет по маршруту", ["opt.GreenLightPriority.D"]="Светофоры на маршруте выехавшей машины переключаются на зелёный при её приближении и остаются зелёными, пока она не проедет. Это разгружает очередь машин перед ней: сами экстренные машины и так проезжают на красный, ждёт именно транспорт впереди них. Используется собственный механизм приоритета светофоров игры, поэтому обычные фазы и пешеходные переходы по-прежнему соблюдаются.", ["opt.GreenLightDistance.L"]="Дальность действия зелёного света (метры)", ["opt.GreenLightDistance.D"]="На каком расстоянии перед выехавшей машиной реагируют светофоры. Безопасное переключение занимает несколько секунд, поэтому большая дальность повышает шанс, что к моменту прибытия уже горит зелёный. Меньшая дальность удерживает открытыми меньше перекрёстков одновременно.", ["grp.Group"]="Выезжающие машины", ["grp.GroupLights"]="Светофоры", ["grp.GroupGeneral"]="Общие", },
                ["zh-HANS"] = new Dictionary<string, string> { ["opt.Enabled.L"]="启用紧急优先", ["opt.Enabled.D"]="让正在出勤的消防车、救护车和警车得以在交通拥堵中存活并继续行进。关闭 = 原版行为。", ["opt.DespawnGuard.L"]="防止受困出勤车辆消失", ["opt.DespawnGuard.D"]="原版会在出勤车辆被标记为受困于交通时将其删除，紧急任务则等待重新派遣。启用此保护后，车辆会转而寻找新路线。", ["opt.AutoReroute.L"]="绕开拥堵重新规划路线", ["opt.AutoReroute.D"]="原版只在派遣时规划一次路线。开启此项后，堵在拥堵中的出勤车辆会请求一条考虑当前交通状况的新路线。", ["opt.RerouteAfterSeconds.L"]="多少秒后重新规划路线（受阻秒数）", ["opt.RerouteAfterSeconds.D"]="出勤车辆必须连续受阻于交通多久后才会寻找绕行路线。", ["opt.GreenLightPriority.L"]="沿途路口亮绿灯", ["opt.GreenLightPriority.D"]="出勤车辆路线上的红绿灯会在其接近时变绿，并保持绿灯直到车辆通过。这是为了疏散它前方排队的车辆——紧急车辆本身原本就会闯红灯，等待的是它前面的普通车流。使用游戏自带的信号优先机制，因此正常的信号相位和人行横道依然会被遵守。", ["opt.GreenLightDistance.L"]="绿灯响应距离（米）", ["opt.GreenLightDistance.D"]="红绿灯会在出勤车辆前方多远处开始响应。信号灯安全切换需要几秒钟，因此距离越长，车辆抵达时已经是绿灯的可能性越大。距离越短，同时被打开的路口就越少。", ["grp.Group"]="出勤车辆", ["grp.GroupLights"]="红绿灯", ["grp.GroupGeneral"]="常规", },
                ["zh-HANT"] = new Dictionary<string, string> { ["opt.Enabled.L"]="啟用緊急優先", ["opt.Enabled.D"]="讓出勤中的消防車、救護車與警車在塞車中維持存在並持續移動。關閉＝原版行為。", ["opt.DespawnGuard.L"]="防止受困的出勤車輛消失", ["opt.DespawnGuard.D"]="原版在出勤車輛被標記為卡在車陣中後便將其刪除，緊急事件則等待重新派遣。啟用防護後，車輛會改為尋找新路線。", ["opt.AutoReroute.L"]="繞過壅塞重新規劃路線", ["opt.AutoReroute.D"]="原版只在派遣當下規劃一次路線。啟用後，卡在車陣中動彈不得的出勤車輛會請求一條考量當前交通狀況的新路線。", ["opt.RerouteAfterSeconds.L"]="重新規劃路線前等待（受阻秒數）", ["opt.RerouteAfterSeconds.D"]="出勤車輛在尋找繞道前，必須連續卡在車陣後方多久。", ["opt.GreenLightPriority.L"]="沿途路口亮綠燈", ["opt.GreenLightPriority.D"]="出勤車輛路線上的紅綠燈會在其接近時轉為綠燈，並維持綠燈直到車輛通過。這是為了疏散前方排隊的車流——緊急車輛本身原本就會闖紅燈，等待的是它前方的一般車流。使用遊戲內建的號誌優先機制，因此正常的號誌相位與行人穿越道仍會被遵守。", ["opt.GreenLightDistance.L"]="綠燈反應距離（公尺）", ["opt.GreenLightDistance.D"]="紅綠燈會在出勤車輛前方多遠處開始反應。號誌安全切換需要幾秒鐘，因此距離越長，車輛抵達時已經是綠燈的可能性越高。距離越短，同時開放的路口就越少。", ["grp.Group"]="出勤車輛", ["grp.GroupLights"]="紅綠燈", ["grp.GroupGeneral"]="一般", },
        };
    }
}
